# Generated by Django 3.2.9 on 2024-05-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="role",
            field=models.CharField(
                choices=[("AUTHOR", "Author"), ("CONTRIBUTOR", "Contributor")],
                default="CONTRIBUTOR",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(default=18),
        ),
    ]
